FROM golang:1.17-buster as BUILD
WORKDIR /testdir
RUN go get github.com/mattn/go-sqlite3@v1.14.7
RUN go get github.com/onsi/ginkgo@v1.15.1
RUN go get github.com/onsi/gomega@v1.11.0
COPY . .
ENTRYPOINT ["go", "test", "./...", "-count=1"]