// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	types "github.com/barcostreams/barco/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// Replicator is an autogenerated mock type for the Replicator type
type Replicator struct {
	mock.Mock
}

// SendToFollowers provides a mock function with given fields: replicationInfo, topic, segmentId, chunk
func (_m *Replicator) SendToFollowers(replicationInfo types.ReplicationInfo, topic types.TopicDataId, segmentId int64, chunk types.SegmentChunk) error {
	ret := _m.Called(replicationInfo, topic, segmentId, chunk)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.ReplicationInfo, types.TopicDataId, int64, types.SegmentChunk) error); ok {
		r0 = rf(replicationInfo, topic, segmentId, chunk)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
