// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	io "io"

	interbroker "github.com/barcostreams/barco/internal/interbroker"

	mock "github.com/stretchr/testify/mock"

	types "github.com/barcostreams/barco/internal/types"

	url "net/url"

	uuid "github.com/google/uuid"
)

// Gossiper is an autogenerated mock type for the Gossiper type
type Gossiper struct {
	mock.Mock
}

// AcceptConnections provides a mock function with given fields:
func (_m *Gossiper) AcceptConnections() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *Gossiper) Close() {
	_m.Called()
}

// GetGenerations provides a mock function with given fields: ordinal, token
func (_m *Gossiper) GetGenerations(ordinal int, token types.Token) interbroker.GenReadResult {
	ret := _m.Called(ordinal, token)

	var r0 interbroker.GenReadResult
	if rf, ok := ret.Get(0).(func(int, types.Token) interbroker.GenReadResult); ok {
		r0 = rf(ordinal, token)
	} else {
		r0 = ret.Get(0).(interbroker.GenReadResult)
	}

	return r0
}

// HasTokenHistoryForToken provides a mock function with given fields: ordinal, token, clusterSize
func (_m *Gossiper) HasTokenHistoryForToken(ordinal int, token types.Token, clusterSize int) (bool, error) {
	ret := _m.Called(ordinal, token, clusterSize)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, types.Token, int) bool); ok {
		r0 = rf(ordinal, token, clusterSize)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, types.Token, int) error); ok {
		r1 = rf(ordinal, token, clusterSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *Gossiper) Init() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsHostUp provides a mock function with given fields: ordinal
func (_m *Gossiper) IsHostUp(ordinal int) bool {
	ret := _m.Called(ordinal)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(ordinal)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsTokenRangeCovered provides a mock function with given fields: ordinal, token
func (_m *Gossiper) IsTokenRangeCovered(ordinal int, token types.Token) (bool, error) {
	ret := _m.Called(ordinal, token)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, types.Token) bool); ok {
		r0 = rf(ordinal, token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, types.Token) error); ok {
		r1 = rf(ordinal, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergeTopicFiles provides a mock function with given fields: peers, topic, offset
func (_m *Gossiper) MergeTopicFiles(peers []int, topic *types.TopicDataId, offset int64) error {
	ret := _m.Called(peers, topic, offset)

	var r0 error
	if rf, ok := ret.Get(0).(func([]int, *types.TopicDataId, int64) error); ok {
		r0 = rf(peers, topic, offset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OpenConnections provides a mock function with given fields:
func (_m *Gossiper) OpenConnections() {
	_m.Called()
}

// RangeSplitStart provides a mock function with given fields: ordinal
func (_m *Gossiper) RangeSplitStart(ordinal int) error {
	ret := _m.Called(ordinal)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(ordinal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadBrokerIsUp provides a mock function with given fields: ordinal, brokerUpOrdinal
func (_m *Gossiper) ReadBrokerIsUp(ordinal int, brokerUpOrdinal int) (bool, error) {
	ret := _m.Called(ordinal, brokerUpOrdinal)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(ordinal, brokerUpOrdinal)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(ordinal, brokerUpOrdinal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadProducerOffset provides a mock function with given fields: ordinal, topic
func (_m *Gossiper) ReadProducerOffset(ordinal int, topic *types.TopicDataId) (int64, error) {
	ret := _m.Called(ordinal, topic)

	var r0 int64
	if rf, ok := ret.Get(0).(func(int, *types.TopicDataId) int64); ok {
		r0 = rf(ordinal, topic)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *types.TopicDataId) error); ok {
		r1 = rf(ordinal, topic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadTokenHistory provides a mock function with given fields: ordinal, token, clusterSize
func (_m *Gossiper) ReadTokenHistory(ordinal int, token types.Token, clusterSize int) (*types.Generation, error) {
	ret := _m.Called(ordinal, token, clusterSize)

	var r0 *types.Generation
	if rf, ok := ret.Get(0).(func(int, types.Token, int) *types.Generation); ok {
		r0 = rf(ordinal, token, clusterSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Generation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, types.Token, int) error); ok {
		r1 = rf(ordinal, token, clusterSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterConsumerInfoListener provides a mock function with given fields: listener
func (_m *Gossiper) RegisterConsumerInfoListener(listener interbroker.ConsumerInfoListener) {
	_m.Called(listener)
}

// RegisterGenListener provides a mock function with given fields: listener
func (_m *Gossiper) RegisterGenListener(listener interbroker.GenListener) {
	_m.Called(listener)
}

// RegisterHostUpDownListener provides a mock function with given fields: listener
func (_m *Gossiper) RegisterHostUpDownListener(listener interbroker.PeerStateListener) {
	_m.Called(listener)
}

// RegisterReroutedMessageListener provides a mock function with given fields: listener
func (_m *Gossiper) RegisterReroutedMessageListener(listener interbroker.ReroutingListener) {
	_m.Called(listener)
}

// SendCommittedOffset provides a mock function with given fields: ordinal, offsetKv
func (_m *Gossiper) SendCommittedOffset(ordinal int, offsetKv *types.OffsetStoreKeyValue) error {
	ret := _m.Called(ordinal, offsetKv)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *types.OffsetStoreKeyValue) error); ok {
		r0 = rf(ordinal, offsetKv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendConsumerCommit provides a mock function with given fields: ordinal, id
func (_m *Gossiper) SendConsumerCommit(ordinal int, id string) error {
	ret := _m.Called(ordinal, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(ordinal, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendConsumerGroups provides a mock function with given fields: ordinal, groups
func (_m *Gossiper) SendConsumerGroups(ordinal int, groups []types.ConsumerGroup) error {
	ret := _m.Called(ordinal, groups)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []types.ConsumerGroup) error); ok {
		r0 = rf(ordinal, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendConsumerRegister provides a mock function with given fields: ordinal, id, group, topics, onNewGroup
func (_m *Gossiper) SendConsumerRegister(ordinal int, id string, group string, topics []string, onNewGroup types.OffsetResetPolicy) error {
	ret := _m.Called(ordinal, id, group, topics, onNewGroup)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, string, []string, types.OffsetResetPolicy) error); ok {
		r0 = rf(ordinal, id, group, topics, onNewGroup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendConsumerUnregister provides a mock function with given fields: ordinal, id
func (_m *Gossiper) SendConsumerUnregister(ordinal int, id string) error {
	ret := _m.Called(ordinal, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(ordinal, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendGoobye provides a mock function with given fields:
func (_m *Gossiper) SendGoobye() {
	_m.Called()
}

// SendToFollowers provides a mock function with given fields: replicationInfo, topic, segmentId, chunk
func (_m *Gossiper) SendToFollowers(replicationInfo types.ReplicationInfo, topic types.TopicDataId, segmentId int64, chunk types.SegmentChunk) error {
	ret := _m.Called(replicationInfo, topic, segmentId, chunk)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.ReplicationInfo, types.TopicDataId, int64, types.SegmentChunk) error); ok {
		r0 = rf(replicationInfo, topic, segmentId, chunk)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendToLeader provides a mock function with given fields: replicationInfo, topic, querystring, contentLength, contentType, body
func (_m *Gossiper) SendToLeader(replicationInfo types.ReplicationInfo, topic string, querystring url.Values, contentLength int64, contentType string, body io.Reader) error {
	ret := _m.Called(replicationInfo, topic, querystring, contentLength, contentType, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.ReplicationInfo, string, url.Values, int64, string, io.Reader) error); ok {
		r0 = rf(replicationInfo, topic, querystring, contentLength, contentType, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAsCommitted provides a mock function with given fields: ordinal, token1, token2, tx
func (_m *Gossiper) SetAsCommitted(ordinal int, token1 types.Token, token2 *types.Token, tx uuid.UUID) error {
	ret := _m.Called(ordinal, token1, token2, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, types.Token, *types.Token, uuid.UUID) error); ok {
		r0 = rf(ordinal, token1, token2, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetGenerationAsProposed provides a mock function with given fields: ordinal, newGen, newGen2, expectedTx
func (_m *Gossiper) SetGenerationAsProposed(ordinal int, newGen *types.Generation, newGen2 *types.Generation, expectedTx *uuid.UUID) error {
	ret := _m.Called(ordinal, newGen, newGen2, expectedTx)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *types.Generation, *types.Generation, *uuid.UUID) error); ok {
		r0 = rf(ordinal, newGen, newGen2, expectedTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StreamFile provides a mock function with given fields: peers, segmentId, topic, startOffset, maxRecords, buf
func (_m *Gossiper) StreamFile(peers []int, segmentId int64, topic *types.TopicDataId, startOffset int64, maxRecords int, buf []byte) (int, error) {
	ret := _m.Called(peers, segmentId, topic, startOffset, maxRecords, buf)

	var r0 int
	if rf, ok := ret.Get(0).(func([]int, int64, *types.TopicDataId, int64, int, []byte) int); ok {
		r0 = rf(peers, segmentId, topic, startOffset, maxRecords, buf)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int, int64, *types.TopicDataId, int64, int, []byte) error); ok {
		r1 = rf(peers, segmentId, topic, startOffset, maxRecords, buf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WaitForPeersUp provides a mock function with given fields:
func (_m *Gossiper) WaitForPeersUp() {
	_m.Called()
}

type mockConstructorTestingTNewGossiper interface {
	mock.TestingT
	Cleanup(func())
}

// NewGossiper creates a new instance of Gossiper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGossiper(t mockConstructorTestingTNewGossiper) *Gossiper {
	mock := &Gossiper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
