---
apiVersion: v1
kind: Service
metadata:
  name: barco
  namespace: barco
spec:
  selector:
    name: barco
  ports:
  - name: discovery
    protocol: TCP
    port: 9250
    targetPort: discovery
  - name: producer
    protocol: TCP
    port: 9251
    targetPort: producer
  - name: consumer
    protocol: TCP
    port: 9252
    targetPort: consumer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: barco
  namespace: barco
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: barco
  namespace: barco
rules:
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get","list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get","list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: barco
  namespace: barco
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: barco
subjects:
  - kind: ServiceAccount
    name: barco
    namespace: barco
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: barco
  namespace: barco
  labels:
      app.kubernetes.io/name: barco
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: barco
      name: barco
  serviceName: barco
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: barco
        name: barco
      annotations:
        prometheus.io/port: "9253"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: barco
      terminationGracePeriodSeconds: 60
      containers:
      - name: barco
        image: barcostreams/barco:latest
        imagePullPolicy: Always
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        ports:
        - containerPort: 9250
          name: discovery
        - containerPort: 9251
          name: producer
        - containerPort: 9252
          name: consumer
        env:
        - name: BARCO_SERVICE_NAME
          value: barco
        - name: BARCO_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BARCO_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTAINER_CPU_REQUEST_MILLICORES
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
              divisor: 1m
        - name: CONTAINER_MEMORY_LIMIT_KIBIBYTES
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
              divisor: 1Ki
